Scrum 39 Fixed_issue_with_life_buffing_enemies
swLevelUp23/levelUp pull request #14
Opened 2023-12-04 08:39 UTC by je0ng3

enemyShipD 객체(생명력 강화 적)가 완전히 제거되기 전에 점수가 계속 카운트되는 문제와 색 변경이 이루어지지 않는 문제 해결했습니다.

2023-12-04 08:44 UTC, thwldus requested changes

2023-12-04 08:44 UTC, thwldus commented on res/scores_1p & non-skill mode
> +90
코드 구현 후 게임을 실행해보면서 게임 기록이 남은 듯 싶습니다.
초기 실행한 게임은 아무 기록이 없는 상태로 유지해야하니 수정 부탁드립니다.

2023-12-04 08:44 UTC, thwldus commented on res/scores_1p & skill mode
> +530
위와 마찬가지입니다.

2023-12-04 08:55 UTC, je0ng3 commented on res/scores_1p & non-skill mode
> +90
네 수정했습니다

2023-12-04 08:55 UTC, je0ng3 commented on res/scores_1p & skill mode
> +530
네 수정했습니다

2023-12-04 08:58 UTC, oneyVerde approved these changes

2023-12-04 17:03 UTC, thwldus requested changes

2023-12-04 17:03 UTC, thwldus commented on src/screen/GameScreen.java
> -		}
해당 코드는 보스적의 남은 생명을 나타내는 막대바입니다.
이 코드를 지우게 되면 보스의 남은 생명 게이지를 알 수 없으므로, 추가해주시기 바랍니다.

2023-12-04 17:20 UTC, je0ng3 commented on src/screen/GameScreen.java
> -		}
죄송합니다. 추가했습니다.

2023-12-05 03:54 UTC, thwldus approved these changes

2023-12-05 04:11 UTC, merged