Scrum 19 high score screen improve
swLevelUp23/levelUp pull request #8
Opened 2023-11-25 11:12 UTC by iyeongseo

High Score 창에서 1p/2p 모드별 플레이어 랭킹 skill mode on/off인 경우도 고려하여 볼 수 있도록 개선 하였습니다.

2023-11-25 13:12 UTC, thwldus requested changes

2023-11-25 13:12 UTC, thwldus commented on src/engine/DrawManager.java
> +		}
highScores에 저장된 모든 사용자의 기록을 화면에 출력하도록 하고 있네요.
그럼 기록을 남긴 사용자가 많아진다면,  NON-SKILL의 랭킹과 SKILL의 랭킹의 텍스트가 겹쳐지거나 게임 화면 창 범위 밖에서도 반복문이 돌아가는 문제가 생길 것 같습니다. 이를 감안해서 상위 랭킹만 보여주도록 하는 것이 좋을 거 같습니다.

2023-11-25 13:13 UTC, oneyVerde requested changes

2023-11-25 13:13 UTC, oneyVerde commented on src/engine/DrawManager.java
>  		backBufferGraphics.setColor(Color.GRAY);
등수를 나타내는 부분과 구분되도록 mode를 나타내는 글자 색상을 바꾸어도 좋을 것 같습니다

2023-11-26 07:17 UTC, thwldus approved these changes

2023-11-26 10:39 UTC, oneyVerde approved these changes

2023-11-26 11:13 UTC, merged